print("\n")
print("Welcome to the Band Generator")
print("\n")
city = input("What's the name of the city you grew up in? ")
print("\n")
pets_name = input("What's the name of your all-time favorite pet? ")
print("\n")
print("Your band name could be the " + city + " " + pets_name)
print("\n")