print("\n")
print("Day 1 - Sting Manipulation")
print('String Concatenation is done with the "+" sign.')
print('e.g. print("Hello" + "World")')
print("New lines can be created with a backlash and n.")
print("\n")
